schema
  @link(url: "https://specs.apollo.dev/link/v1.0")
  @link(url: "https://specs.apollo.dev/join/v0.3", for: EXECUTION)
  @link(url: "https://specs.apollo.dev/inaccessible/v0.2", for: SECURITY)
{
  query: Query
  mutation: Mutation
}

directive @inaccessible on FIELD_DEFINITION | OBJECT | INTERFACE | UNION | ARGUMENT_DEFINITION | SCALAR | ENUM | ENUM_VALUE | INPUT_OBJECT | INPUT_FIELD_DEFINITION

directive @join__enumValue(graph: join__Graph!) repeatable on ENUM_VALUE

directive @join__field(graph: join__Graph, requires: join__FieldSet, provides: join__FieldSet, type: String, external: Boolean, override: String, usedOverridden: Boolean) repeatable on FIELD_DEFINITION | INPUT_FIELD_DEFINITION

directive @join__graph(name: String!, url: String!) on ENUM_VALUE

directive @join__implements(graph: join__Graph!, interface: String!) repeatable on OBJECT | INTERFACE

directive @join__type(graph: join__Graph!, key: join__FieldSet, extension: Boolean! = false, resolvable: Boolean! = true, isInterfaceObject: Boolean! = false) repeatable on OBJECT | INTERFACE | UNION | ENUM | INPUT_OBJECT | SCALAR

directive @join__unionMember(graph: join__Graph!, member: String!) repeatable on UNION

directive @link(url: String, as: String, for: link__Purpose, import: [link__Import]) repeatable on SCHEMA

input CreateUserInput
  @join__type(graph: USER_SERVICE)
{
  googleId: ID!
  email: String!
  age: Int!
  pseudo: String!
  role: String!
}

scalar join__FieldSet

enum join__Graph {
  USER_SERVICE @join__graph(name: "user-service", url: "http://service-user:3001/graphql")
}

scalar link__Import

enum link__Purpose {
  """
  `SECURITY` features provide metadata necessary to securely resolve fields.
  """
  SECURITY

  """
  `EXECUTION` features provide metadata necessary for operation execution.
  """
  EXECUTION
}

type Mutation
  @join__type(graph: USER_SERVICE)
{
  createUser(createUserInput: CreateUserInput!): User! @inaccessible
  updateUser(updateUserInput: UpdateUserInput!): User! @inaccessible
  removeUser(googleId: String!): User! @inaccessible
  simpleMutation(payload: String!): String!
}

type Query
  @join__type(graph: USER_SERVICE)
{
  getMe: User!
  users: [User!]!
  user(googleId: String!): User!
  simpleQuery: String!
}

input UpdateUserInput
  @join__type(graph: USER_SERVICE)
{
  googleId: ID!
}

type User
  @join__type(graph: USER_SERVICE, key: "googleId")
{
  googleId: ID!
  email: String
  age: Int!
  pseudo: String
  role: String
}